### ISSUE TITLE
Any possibility of a vertical version

### ISSUE THREAD

**Issue by vvv-ca** [inaxeon/ocu2pciex8#1]
Hello,

thanks for providing this! I was looking for a way to use the extra OCulink interfaces to add another network card.
Is there any possibility to provide a version where the PCIe connector is parallel to the the PCB?

Thanks!

**Comment by inaxeon** [comment]
The point of releasing this is that I don't have time to design risers for others.

You could try contacting C_Payne. I believe he designs risers and adapters for a fee!
